// Generates two committed SQL artifacts from the typed seed source of truth
// (src/db/seed.ts), so the `wrangler d1 execute --file=...` path stays in sync
// with the programmatic ensureSeed() path:
//
//   schema.sql      ← copy of migrations/0001_init.sql (the canonical schema)
//   seed/seed.sql   ← idempotent INSERTs for the New Zealand trip
//
// Run via `npm run gen:seed` (tsx).

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSeedRows, SEED_TABLES, TRIP } from "../src/db/seed.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function lit(v: unknown): string {
  if (v === undefined || v === null) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  return `'${String(v).replace(/'/g, "''")}'`;
}

function insert(table: string, row: Record<string, unknown>): string {
  const cols = Object.keys(row);
  const vals = cols.map((c) => lit(row[c]));
  return `INSERT OR REPLACE INTO ${table} (${cols.join(", ")}) VALUES (${vals.join(", ")});`;
}

function tableNameFor(key: string): string {
  return key === "trip" ? "trips" : key;
}

function buildSeedSql(): string {
  const rows = buildSeedRows(TRIP.id);
  const lines: string[] = [
    "-- GENERATED by scripts/gen-seed.ts — do not edit by hand.",
    "-- Idempotent seed for the New Zealand South Island trip. Safe to re-run.",
    "",
    "BEGIN TRANSACTION;",
    "",
    "-- Clear any prior copy of this trip (children first).",
  ];

  for (const key of [...SEED_TABLES].reverse()) {
    const table = tableNameFor(key);
    if (table === "trips") lines.push(`DELETE FROM ${table} WHERE id = ${lit(TRIP.id)};`);
    else lines.push(`DELETE FROM ${table} WHERE trip_id = ${lit(TRIP.id)};`);
  }
  lines.push("");

  for (const key of SEED_TABLES) {
    const table = tableNameFor(key);
    lines.push(`-- ${table}`);
    if (key === "trip") {
      lines.push(insert(table, rows.trip));
    } else {
      for (const row of rows[key] as Record<string, unknown>[]) {
        lines.push(insert(table, row));
      }
    }
    lines.push("");
  }

  lines.push("COMMIT;");
  lines.push("");
  return lines.join("\n");
}

function buildSchemaSql(): string {
  // Concatenate every migration in order so schema.sql (the one-shot
  // `wrangler d1 execute --file=schema.sql` path) always reflects the full
  // schema, not just the initial migration.
  const dir = resolve(root, "migrations");
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  const body = files
    .map((f) => readFileSync(resolve(dir, f), "utf8").replace(/^-- Trip Planner — D1 schema \([^)]*\)\.\n/, "").trim())
    .join("\n\n");
  return (
    "-- GENERATED from migrations/*.sql — do not edit by hand.\n" +
    "-- One-shot schema for `wrangler d1 execute trip-planner --file=schema.sql`.\n\n" +
    body +
    "\n"
  );
}

mkdirSync(resolve(root, "seed"), { recursive: true });
writeFileSync(resolve(root, "seed/seed.sql"), buildSeedSql());
writeFileSync(resolve(root, "schema.sql"), buildSchemaSql());
console.log("Wrote schema.sql and seed/seed.sql");
